# Generated by Django 4.0 on 2022-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chequeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=80, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('account_holders_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_received_date', models.DateField(auto_now_add=True)),
                ('cheque_due_date', models.DateField(auto_now_add=True)),
                ('partial_payment_received', models.FloatField(blank=True, null=True)),
                ('cheque_released', models.DateField(auto_now=True)),
                ('notes_about_transaction', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
