# Generated by Django 4.0 on 2022-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeinfo',
            name='cheque_released_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequeinfo',
            name='cheque_due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chequeinfo',
            name='cheque_received_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chequeinfo',
            name='cheque_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chequeinfo',
            name='partial_payment_received',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
